### ISSUE TITLE
Connect to Google sheet for import/export capabilities

### ISSUE THREAD

**Issue by amunn33** [Tiny-Hands/freedom-link#1]
# Story
For the first stage of this application, we will be very reliant upon information from the FreedomLink Google sheet created by Jon Hudlow. This sheet takes information from exported IRFs and VIFs and turns them into stories that can be sent to donors. It will also be the place where Tiny Hands staff members can see which approve stories, see which stories have been sent, and the donors they have been sent to. Therefore, we will need to be able to both import and export information from/to the sheet. 

# Requirements

Fields that need to be added to Stories tab:
- Red flag priority level, sent date, donor (to keep track of who it was sent to)

Import fields for the Stories tab:
- Full Story, Unique ID, Sent date, Red flag priority level

Import fields for VIFs tab:
- VIF number

Export fields for the Stories tab:
- Sent date, Donor

# Where To Start

- Check out how Stan does imports/exports [here](https://github.com/Tiny-Hands/tinyhands/tree/develop/application/export_import). We may want to look into making this our own Python package, or else we will end up duplicating this code over the two repos.
- [This](https://docs.google.com/a/tinyhandsintl.org/spreadsheets/d/14HIaCeqkUfrdq3DGncv6wKkOMF0oHuVQuj9gpURb6iI/edit?usp=sharing) is a copy of the spread sheet that we will need to be working with.

# Questions
- What are the necessary steps for getting the google_sheets authorization that you have set up for our staging and production environments? @scrishel

**Comment by scrishel** [comment]
For Authorization:
Access to google sheets from an application requires a google service account key.  We currently have 3 service account keys - for local, staging and production.  When creating an service account key, a JSON format credentials file is provided by google.  Using the credential file, the application can access google services.  As part of creating the credentials, a client email address is created (for our local, it is tinyhands@project-id-iugctjhyziulokrotpc.iam.gserviceaccount.com).  The owner of a spreadsheet can then share the spreadsheet with the client email address and specify the access level.

We could just share the new spreadsheet(s) required for FreedomLink with our current service account and use the same credentials file.  Alternatively we could create a new service account for FreedomLink that just has access to the spreadsheet that it needs.

**Comment by scrishel** [comment]
If we are looking to create an import/export python package, I believe it would include the files google_sheet_basic.py, google_sheet_import.py, google_sheet_names.py and google_sheet.py.  Note that google_sheet_import.py has two static methods at the bottom of the file that we would not want to include in the package. The two static methods would need to be placed in a new file and remain with the current project.

**Comment by amunn33** [comment]
FreedomLink is being shut down
